/**
 * Demo certification report payload. Replace with API response when wired.
 */

export type CertReport = {
  requestId: string;
  certificationNo: string;
  pcgsNo: string;
  dateMintmark: string;
  denomination: string;
  region: string;
  grade: string;
  pedigree: string;
  mintage: string;
  holderType: string;
  population: string;
  popHigher: string;
  priceGuideValue: string;
};

const BASE_REPORT: Omit<CertReport, "requestId"> = {
  certificationNo: "34464855",
  pcgsNo: "7358",
  dateMintmark: "1890-CC",
  denomination: "$1",
  region: "The United States of America",
  grade: "MS64+",
  pedigree: "De Miller",
  mintage: "12,500,000",
  holderType: "PCGS Gold Shield",
  population: "26",
  popHigher: "3",
  priceGuideValue: "$1,500",
};

/** Returns a PCGS-style demo row for any request id (swap for API lookup). */
export function getCertReportForRequest(requestId: string): CertReport {
  return {
    requestId,
    ...BASE_REPORT,
  };
}

export function certReportDownloadFilename(report: CertReport): string {
  const safe = report.certificationNo.replace(/\s+/g, "");
  return `Coinzy-CERT-${safe}.html`;
}

/** Self-contained HTML for download (open in browser → Print → Save as PDF). */
export function buildCertReportDownloadHtml(report: CertReport): string {
  const title = `CERT VERIFICATION #${report.certificationNo}`;
  const rows: [string, string][] = [
    ["PCGS #", report.pcgsNo],
    ["Date, Mintmark", report.dateMintmark],
    ["Denomination", report.denomination],
    ["Region", report.region],
    ["Grade", report.grade],
    ["Pedigree", report.pedigree],
    ["Mintage", report.mintage],
    ["Holder Type", report.holderType],
    ["Population", report.population],
    ["Pop Higher", report.popHigher],
    ["PCGS Price Guide™ Value", report.priceGuideValue],
  ];

  const tableRows = rows
    .map(
      ([k, v], i) =>
        `<tr style="background:${i % 2 === 0 ? "#f9fafb" : "#fff"}"><td style="padding:10px 14px;font-weight:600;color:#374151;width:38%;border-bottom:1px solid #e5e7eb">${escapeHtml(k)}</td><td style="padding:10px 14px;color:#111827;border-bottom:1px solid #e5e7eb">${escapeHtml(v)}</td></tr>`,
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; margin: 0; padding: 32px; background: #f3f4f6; color: #111827; }
    .wrap { max-width: 720px; margin: 0 auto; background: #fff; padding: 32px; border-radius: 12px; box-shadow: 0 8px 30px rgba(0,0,0,.08); }
    .hint { font-size: 13px; color: #4b5563; margin-bottom: 24px; padding: 12px 16px; background: #eff6ff; border-radius: 8px; border: 1px solid #bfdbfe; }
    h1 { font-size: 22px; letter-spacing: .04em; margin: 0 0 8px; }
    .sub { color: #6b7280; font-size: 14px; margin-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
  </style>
</head>
<body>
  <div class="wrap">
    <p class="hint"><strong>Save as PDF:</strong> Open this file in Chrome or Edge, press <strong>Ctrl+P</strong> (⌘P on Mac), and choose <strong>Save as PDF</strong>.</p>
    <p style="font-size:12px;color:#2563eb;margin:0 0 16px">Coinzy request: ${escapeHtml(report.requestId)}</p>
    <h1>${escapeHtml(title)}</h1>
    <p class="sub">PCGS Coin Information — According to the PCGS Certification Database, the requested certification number is defined as the following:</p>
    <table>${tableRows}</table>
    <p style="margin-top:24px;font-size:12px;color:#9ca3af">Generated by Coinzy (demo). Not affiliated with PCGS.</p>
  </div>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
